// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleGalleryApplication.Data;

namespace SimpleGalleryApplication.Data.Migrations
{
    [DbContext(typeof(SimpleImageGalleryDbContext))]
    [Migration("20180907090909_Initial Migration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SimpleGalleryApplication.Data.Models.GalleryImage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<string>("Title");

                    b.Property<string>("Url");

                    b.HasKey("ID");

                    b.ToTable("GalleryImages");
                });

            modelBuilder.Entity("SimpleGalleryApplication.Data.Models.ImageTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<int?>("GalleryImageID");

                    b.HasKey("Id");

                    b.HasIndex("GalleryImageID");

                    b.ToTable("ImageTage");
                });

            modelBuilder.Entity("SimpleGalleryApplication.Data.Models.ImageTag", b =>
                {
                    b.HasOne("SimpleGalleryApplication.Data.Models.GalleryImage")
                        .WithMany("ImageTags")
                        .HasForeignKey("GalleryImageID");
                });
#pragma warning restore 612, 618
        }
    }
}
